#include "search.h"
#include "../core/movegen.h"
#include "../evaluation/eval.h"
#include "../tb/syzygy.h"
#include <algorithm>
#include <chrono>
#include <future>
#include <thread>
#include <cmath>

namespace chess {
namespace {
int piece_value(Piece p) { switch (p) { case Piece::WP: case Piece::BP: return 100; case Piece::WN: case Piece::BN: return 320; case Piece::WB: case Piece::BB: return 330; case Piece::WR: case Piece::BR: return 500; case Piece::WQ: case Piece::BQ: return 900; default: return 0; } }
int promo_bonus(std::uint32_t promo) { switch (promo) { case 1:return 320; case 2:return 330; case 3:return 500; case 4:return 900; default:return 0; } }
int piece_type_slot(Piece p) { switch(p){case Piece::WP:return 0;case Piece::WN:return 1;case Piece::WB:return 2;case Piece::WR:return 3;case Piece::WQ:return 4;case Piece::WK:return 5;case Piece::BP:return 6;case Piece::BN:return 7;case Piece::BB:return 8;case Piece::BR:return 9;case Piece::BQ:return 10;case Piece::BK:return 11;default:return -1;} }
}
inline Score value_from_tt(Score v,int ply){if(v>=30000-1000)return v-ply;if(v<=-30000+1000)return v+ply;return v;}
inline Score value_to_tt(Score v,int ply){if(v>=30000-1000)return v+ply;if(v<=-30000+1000)return v-ply;return v;}
void Search::init_tables(){for(int d=1;d<64;++d)for(int m=1;m<64;++m)lmr_table_[d][m]=static_cast<int>(0.75+std::log(d)*std::log(m)*0.35);for(int d=0;d<16;++d){futility_margin_[d]=150*d+80;reverse_futility_margin_[d]=120*d+60;probcut_margin_[d]=200+90*d;}}
int Search::piece_slot(Piece p){return piece_type_slot(p);}
bool Search::time_up()const{if(limit_ms_<=0)return false;return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()-start_).count()>=limit_ms_;}
int Search::complexity_score(const Position& pos)const{MoveList moves;Position copy=pos;generate_moves(copy,moves,false);int material=0,pawns=0;for(int sq=0;sq<64;++sq){Piece p=pos.board()[sq];if(p==Piece::None)continue;material+=piece_value(p);if(p==Piece::WP||p==Piece::BP)++pawns;}int c=pos.in_check(pos.side_to_move())?40:0;c+=std::min(40,moves.size*2);if(material<2400)c+=25;if(pawns<=6)c+=20;int caps=0;for(int i=0;i<moves.size;++i)if(moves.moves[i].flags()&FLAG_CAPTURE)++caps;return c+std::min(20,caps*5);}
int Search::adaptive_depth(const Position& pos,const Limits& limits)const{if(limits.depth>0)return limits.depth;int c=complexity_score(pos),base=c<35?18:c<60?22:c<85?26:c<110?30:34;if(limit_ms_>0)base=limit_ms_<800?std::min(base,14):limit_ms_<1500?std::min(base,18):limit_ms_<4000?std::min(base,22):limit_ms_<10000?std::min(base,26):std::min(base,30);return std::clamp(base,12,40);}
int Search::score_move(const Position& pos,Move m,Move tt_move,int ply)const{if(m.raw==tt_move.raw)return 2000000;const auto&b=pos.board();Piece fromP=b[m.from()],toP=b[m.to()];int s=0;if(m.flags()&FLAG_CAPTURE){Piece victim=toP;if(m.flags()&FLAG_EN_PASSANT)victim=pos.side_to_move()==Color::White?Piece::BP:Piece::WP;int seeScore=see(pos,m);s+=1000000+piece_value(victim)*10-piece_value(fromP)/10+seeScore*2;int slot=piece_slot(fromP);if(slot>=0)s+=capture_history_[static_cast<int>(pos.side_to_move())][slot%6][m.to()]/4;}else{int slot=piece_slot(fromP);if(slot>=0)s+=history_[slot][m.to()];if(ply>0&&slot>=0)s+=cont_history_[slot][m.from()][m.to()]/2;if(killers_[ply][0].raw==m.raw)s+=90000;else if(killers_[ply][1].raw==m.raw)s+=80000;}if(m.flags()&FLAG_PROMOTION)s+=900000+promo_bonus(m.promo());return s;}
void Search::order_moves(Position& pos,MoveList& moves,Move tt_move,int ply)const{std::array<std::pair<int,Move>,256> scored{};for(int i=0;i<moves.size;++i)scored[i]={score_move(pos,moves.moves[i],tt_move,ply);moves.moves[i]};std::sort(scored.begin(),scored.begin()+moves.size,[](const auto&a,const auto&b){return a.first>b.first;});for(int i=0;i<moves.size;++i)moves.moves[i]=scored[i].second;}
Score Search::qsearch(Position& pos,Score alpha,Score beta,int ply){seldepth_=std::max(seldepth_,ply);++nodes_;if(time_up()||ply>=MAX_PLY-1)return evaluate(pos);if(pos.is_draw(ply))return 0;auto*ttEntry=tt_.probe(pos.zobrist());Move tt_move{};if(ttEntry&&ttEntry->key==pos.zobrist()){tt_move=ttEntry->best;Score t=value_from_tt(ttEntry->score,ply);if(ttEntry->depth>=0&&std::abs(t)<10000){if(ttEntry->flag==TTFlag::Exact)return t;if(ttEntry->flag==TTFlag::Beta&&t>=beta)return t;if(ttEntry->flag==TTFlag::Alpha&&t<=alpha)return t;}}Score stand=evaluate(pos);if(stand>=beta)return beta;if(stand>alpha)alpha=stand;MoveList moves;if(pos.in_check(pos.side_to_move()))generate_moves(pos,moves,false);else generate_moves(pos,moves,true);order_moves(pos,moves,tt_move,ply);for(int i=0;i<moves.size;++i){Move m=moves.moves[i];if(!see_ge(pos,m,-50))continue;if(!pos.make_move(m))continue;if(pos.in_check(opposite(pos.side_to_move()))){pos.unmake_move();continue;}Score sc=-qsearch(pos,-beta,-alpha,ply+1);pos.unmake_move();if(sc>=beta)return beta;if(sc>alpha)alpha=sc;if(time_up())break;}return alpha;}
Score Search::negamax(Position& pos,int depth,Score alpha,Score beta,int ply,bool cutNode){seldepth_=std::max(seldepth_,ply);++nodes_;if(time_up())return evaluate(pos);if(depth<=0||ply>=MAX_PLY-1)return depth<=0?qsearch(pos,alpha,beta,ply):evaluate(pos);if(pos.is_draw(ply))return 0;bool in_check=pos.in_check(pos.side_to_move());if(in_check)++depth;tt_.prefetch(pos.zobrist());auto*tte=tt_.probe(pos.zobrist());Move tt_move{};if(tte&&tte->key==pos.zobrist()){tt_move=tte->best;Score t=value_from_tt(tte->score,ply);if(ply>0&&tte->depth>=depth){if(tte->flag==TTFlag::Exact)return t;if(tte->flag==TTFlag::Beta&&t>=beta)return t;if(tte->flag==TTFlag::Alpha&&t<=alpha)return t;}}Score staticEval=evaluate(pos);MoveList moves;generate_moves(pos,moves,false);if(moves.size==0)return in_check?-MATE_SCORE+ply:0;order_moves(pos,moves,tt_move,ply);Score alpha0=alpha,beta0=beta,best_score=-INF;Move best{};int tried=0;for(int i=0;i<moves.size;++i){Move m=moves.moves[i];bool cap=(m.flags()&FLAG_CAPTURE)||pos.board()[m.to()]!=Piece::None;if(!in_check&&depth<=6&&!cap&&!see_ge(pos,m,-depth*depth*10)){++tried;continue;}if(!pos.make_move(m))continue;Score sc=-negamax(pos,depth-1,-beta,-alpha,ply+1,!cutNode);pos.unmake_move();++tried;if(time_up())break;if(sc>best_score){best_score=sc;best=m;}if(sc>alpha)alpha=sc;if(alpha>=beta)break;}if(tried==0)return in_check?-MATE_SCORE+ply:0;TTFlag flag=best_score<=alpha0?TTFlag::Alpha:best_score>=beta0?TTFlag::Beta:TTFlag::Exact;tt_.store(pos.zobrist(),depth,best_score,flag,best,staticEval,ply);return best_score;}
std::vector<Move> Search::extract_pv(Position pos,int depth)const{std::vector<Move>pv;for(int i=0;i<depth;++i){auto*e=tt_.probe(pos.zobrist());if(!e||e->best.is_null())break;MoveList legal;generate_moves(pos,legal,false);bool found=false;for(int j=0;j<legal.size;++j)if(legal.moves[j].raw==e->best.raw)found=true;if(!found||!pos.make_move(e->best))break;pv.push_back(e->best);}return pv;}
SearchResult Search::think(Position&pos,const Limits&limits){SearchResult r;nodes_=0;seldepth_=0;start_=std::chrono::steady_clock::now();tt_.new_search();limit_ms_=limits.movetime_ms;int max_depth=adaptive_depth(pos,limits);MoveList root;generate_moves(pos,root,false);if(root.size==0){r.best_move=Move{};r.score=pos.in_check(pos.side_to_move())?-MATE_SCORE:0;return r;}Move best{};Score best_score=-INF;for(int depth=1;depth<=max_depth&&!time_up();++depth){Move tt_move{};if(auto*e=tt_.probe(pos.zobrist()))tt_move=e->best;order_moves(pos,root,tt_move,0);Score alpha=-INF;for(int i=0;i<root.size;++i){Move m=root.moves[i];if(!pos.make_move(m))continue;Score sc=-negamax(pos,depth-1,-INF,-alpha,1,false);pos.unmake_move();if(sc>best_score){best_score=sc;best=m;}if(sc>alpha)alpha=sc;}r.best_move=best;r.score=best_score;r.depth=depth;}r.nodes=nodes_;r.seldepth=seldepth_;r.pv={best};return r;}
} // namespace chess
