#include "search.h"
#include "../core/movegen.h"
#include "../evaluation/eval.h"
#include "../tb/syzygy.h"
#include <algorithm>
#include <chrono>
#include <future>
#include <thread>
#include <cmath>
namespace chess { namespace { int piece_value(Piece p){switch(p){case Piece::WP:case Piece::BP:return 100;case Piece::WN:case Piece::BN:return 320;case Piece::WB:case Piece::BB:return 330;case Piece::WR:case Piece::BR:return 500;case Piece::WQ:case Piece::BQ:return 900;default:return 0;}} int promo_bonus(std::uint32_t p){return p==1?320:p==2?330:p==3?500:p==4?900:0;} int piece_type_slot(Piece p){switch(p){case Piece::WP:return 0;case Piece::WN:return 1;case Piece::WB:return 2;case Piece::WR:return 3;case Piece::WQ:return 4;case Piece::WK:return 5;case Piece::BP:return 6;case Piece::BN:return 7;case Piece::BB:return 8;case Piece::BR:return 9;case Piece::BQ:return 10;case Piece::BK:return 11;default:return -1;}} }
inline Score value_from_tt(Score v,int ply){return v>=29000?v-ply:v<=-29000?v+ply:v;} inline Score value_to_tt(Score v,int ply){return v>=29000?v+ply:v<=-29000?v-ply:v;}
void Search::init_tables(){for(int d=1;d<64;++d)for(int m=1;m<64;++m)lmr_table_[d][m]=static_cast<int>(.75+std::log(d)*std::log(m)*.35);for(int d=0;d<16;++d){futility_margin_[d]=150*d+80;reverse_futility_margin_[d]=120*d+60;probcut_margin_[d]=200+90*d;}}
int Search::piece_slot(Piece p){return piece_type_slot(p);} bool Search::time_up()const{return limit_ms_>0&&std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()-start_).count()>=limit_ms_;}
int Search::complexity_score(const Position& pos)const{MoveList m;Position c=pos;generate_moves(c,m,false);int material=0,pawns=0;for(int s=0;s<64;++s){Piece p=pos.board()[s];if(p==Piece::None)continue;material+=piece_value(p);if(p==Piece::WP||p==Piece::BP)++pawns;}int x=pos.in_check(pos.side_to_move())?40:0;x+=std::min(40,m.size*2)+(material<2400?25:0)+(pawns<=6?20:0);return x;}
int Search::adaptive_depth(const Position& p,const Limits& l)const{if(l.depth>0)return l.depth;int c=complexity_score(p);return std::clamp(c<35?18:c<60?22:c<85?26:c<110?30:34,12,40);}
int Search::score_move(const Position& pos,Move m,Move tt,int ply)const{if(m.raw==tt.raw)return 2000000;Piece a=pos.board()[m.from()],v=pos.board()[m.to()];int s=0;if(m.flags()&FLAG_CAPTURE){if(m.flags()&FLAG_EN_PASSANT)v=pos.side_to_move()==Color::White?Piece::BP:Piece::WP;s+=1000000+piece_value(v)*10-piece_value(a)/10+see(pos,m)*2;int sl=piece_slot(a);if(sl>=0)s+=capture_history_[static_cast<int>(pos.side_to_move())][sl%6][m.to()]/4;}else{int sl=piece_slot(a);if(sl>=0)s+=history_[sl][m.to()];if(ply>0&&sl>=0)s+=cont_history_[sl][m.from()][m.to()]/2;if(killers_[ply][0].raw==m.raw)s+=90000;else if(killers_[ply][1].raw==m.raw)s+=80000;}return s+(m.flags()&FLAG_PROMOTION?900000+promo_bonus(m.promo()):0);}
void Search::order_moves(Position& p,MoveList& m,Move tt,int ply)const{std::array<std::pair<int,Move>,256>s{};for(int i=0;i<m.size;++i)s[i]=std::make_pair(score_move(p,m.moves[i],tt,ply),m.moves[i]);std::sort(s.begin(),s.begin()+m.size,[](auto&a,auto&b){return a.first>b.first;});for(int i=0;i<m.size;++i)m.moves[i]=s[i].second;}
Score Search::qsearch(Position& p,Score a,Score b,int ply){++nodes_;if(time_up()||ply>=MAX_PLY-1)return evaluate(p);if(p.is_draw(ply))return 0;auto*e=tt_->probe(p.zobrist());Move tt{};if(e&&e->key==p.zobrist()){tt=e->best;Score v=value_from_tt(e->score,ply);if(e->depth>=0&&std::abs(v)<10000&&(e->flag==TTFlag::Exact||(e->flag==TTFlag::Beta&&v>=b)||(e->flag==TTFlag::Alpha&&v<=a)))return v;}Score stand=evaluate(p);if(stand>=b)return b;if(stand>a)a=stand;MoveList ms;if(p.in_check(p.side_to_move()))generate_moves(p,ms,false);else generate_moves(p,ms,true);order_moves(p,ms,tt,ply);for(int i=0;i<ms.size;++i){Move m=ms.moves[i];if(!see_ge(p,m,-50)||!p.make_move(m))continue;if(p.in_check(opposite(p.side_to_move()))){p.unmake_move();continue;}Score v=-qsearch(p,-b,-a,ply+1);p.unmake_move();if(v>=b)return b;if(v>a)a=v;}return a;}
Score Search::negamax(Position& p,int d,Score a,Score b,int ply,bool cut){++nodes_;if(time_up())return evaluate(p);if(d<=0)return qsearch(p,a,b,ply);if(p.is_draw(ply))return 0;bool check=p.in_check(p.side_to_move());if(check)++d;tt_->prefetch(p.zobrist());auto*e=tt_->probe(p.zobrist());Move tt{};if(e&&e->key==p.zobrist()){tt=e->best;Score v=value_from_tt(e->score,ply);if(ply>0&&e->depth>=d&&(e->flag==TTFlag::Exact||(e->flag==TTFlag::Beta&&v>=b)||(e->flag==TTFlag::Alpha&&v<=a)))return v;}Score se=evaluate(p);MoveList ms;generate_moves(p,ms,false);if(ms.size==0)return check?-MATE_SCORE+ply:0;order_moves(p,ms,tt,ply);Score a0=a,b0=b,best=-INF;Move bm{};int tried=0;for(int i=0;i<ms.size;++i){Move m=ms.moves[i];if(!check&&d<=6&&!(m.flags()&FLAG_CAPTURE)&&!see_ge(p,m,-d*d*10)){++tried;continue;}if(!p.make_move(m))continue;Score v=-negamax(p,d-1,-b,-a,ply+1,!cut);p.unmake_move();++tried;if(v>best){best=v;bm=m;}if(v>a)a=v;if(a>=b)break;}if(!tried)return check?-MATE_SCORE+ply:0;TTFlag f=best<=a0?TTFlag::Alpha:best>=b0?TTFlag::Beta:TTFlag::Exact;tt_->store(p.zobrist(),d,best,f,bm,se,ply);return best;}
std::vector<Move> Search::extract_pv(Position p,int d)const{std::vector<Move>pv;for(int i=0;i<d;++i){auto*e=tt_->probe(p.zobrist());if(!e||e->best.is_null())break;if(!p.make_move(e->best))break;pv.push_back(e->best);}return pv;}
SearchResult Search::think(Position& p,const Limits& l){SearchResult r;nodes_=0;seldepth_=0;start_=std::chrono::steady_clock::now();tt_->new_search();limit_ms_=l.movetime_ms;MoveList root;generate_moves(p,root,false);if(root.size==0){r.best_move=Move{};r.score=p.in_check(p.side_to_move())?-MATE_SCORE:0;return r;}Move best{};Score bs=-INF;for(int d=1;d<=adaptive_depth(p,l)&&!time_up();++d){Move tt{};if(auto*e=tt_->probe(p.zobrist()))tt=e->best;order_moves(p,root,tt,0);Score a=-INF;for(int i=0;i<root.size;++i){Move m=root.moves[i];if(!p.make_move(m))continue;Score v=-negamax(p,d-1,-INF,-a,1,false);p.unmake_move();if(v>bs){bs=v;best=m;}if(v>a)a=v;}r.best_move=best;r.score=bs;r.depth=d;}r.nodes=nodes_;r.seldepth=seldepth_;r.pv={best};return r;}
} // namespace chess
